Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,9 +24,37 @@ jobs:
     - name: Run tests with coverage
       run: dotnet test Testing.sln --no-build --collect:"XPlat Code Coverage" /p:CoverletOutputFormat=lcov /p:CoverletOutput=./coverage/
 
-    - name: Find coverage file
+    - name: Verify coverage file
+      run: |
+        if [ ! -f ./coverage/coverage.info ]; then
+          echo "Coverage file not found!"
+          exit 1
+        fi
+
+    - name: Set coverage file path
       id: coverage-file
-      run: echo "coverage_file=$(find . -name coverage.info)" >> $GITHUB_ENV
+      run: echo "coverage_file=./coverage/coverage.info" >> $GITHUB_ENV
+
+    - name: Code Coverage Report
+      id: coverage-summary
+      uses: irongut/CodeCoverageSummary@v1.3.0
+      with:
+        filename: ${{ env.coverage_file }}
+        badge: true
+        fail_below_min: true
+        format: markdown
+        hide_branch_rate: true
+        hide_complexity: true
+        indicators: true
+        output: both
+        thresholds: '60 80'
+
+    - name: Add Coverage PR Comment
+      if: github.event_name == 'pull_request'
+      uses: marocchino/sticky-pull-request-comment@v2
+      with:
+        recreate: true
+        path: code-coverage-results.md
 
     - name: Generate Code Coverage report
       id: code-coverage
